### ISSUE TITLE
Unknown CMake command "debug_message".

### ISSUE THREAD

**Issue by mintar** [ros/common_msgs#26] opened 2014-01-30 20:07 UTC
The latest Hydro update broke action message generation using rosmake.

**Steps to reproduce:**

```
source /opt/ros/hydro/setup.zsh
cd katana_msgs
export ROS_PACKAGE_PATH=$(pwd):$ROS_PACKAGE_PATH
rosmake
```

This produces the following error:

```
  -- Action Files:JointMovement.action
  -- Generating Messages for ActionJointMovement.action
  CMake Error at /opt/ros/hydro/share/cpp_common/cmake/cpp_commonConfig.cmake:49 (debug_message):
    Unknown CMake command "debug_message".
  Call Stack (most recent call first):
    /opt/ros/hydro/share/message_runtime/cmake/message_runtimeConfig.cmake:177 (_pack_libraries_with_build_configuration)
    /opt/ros/hydro/share/actionlib_msgs/cmake/actionlib_msgsConfig.cmake:167 (find_package)
    /opt/ros/hydro/share/actionlib_msgs/cmake/actionbuild.cmake:30 (find_package)
    CMakeLists.txt:14 (genaction)
```

This happens for any package that contains an action definition.

**Workaround:**

Inserting

```
include(/opt/ros/hydro/share/catkin/cmake/debug_message.cmake)
```

into

```
/opt/ros/hydro/share/actionlib_msgs/cmake/actionbuild.cmake
```

"fixes" the problem.

I know this is probably not the correct place to report this, and that the error is somewhere else, but since the only thing to go with is actionbuild.cmake from this repo, I'm reporting this here.

**Comment by dirk-thomas** [comment] 2014-01-30 20:16
Duplicate of ros/catkin#583. The fix will be available via Debian packages hopefully by the end of the week.

**Comment by tfoote** [comment] 2014-01-30 20:16
Thanks this is a regression upstream. Ticketed here: https://github.com/ros/catkin/issues/583 We're rolling new debs asap.

**Closed as completed by dirk-thomas** 2014-01-30 20:16 UTC
Labels: duplicate
